import './matchMedia.mock';
import './currencies.mock';
import './stripesConfig.mock';
import './stripesCore.mock';
import './stripesIcon.mock';
import './stripesSmartComponents.mock';
import './stripesComponents.mock';
import './intl.mock';
import './resizeObserver.mock';
